import Link from "next/link";
import { ArticleCard } from "@/components/article-card";
import { getArticles } from "@/lib/articles";
import { categories } from "@/lib/site";
export default function HomePage() {
  const articles = getArticles(); const featured = articles.filter((a) => a.featured).slice(0, 3);
  return <>
    <section className="hero"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> PC / GAMING / AI — FIELD NOTES</p><h1>ゲーム・AI・動画編集の<br /><span>PC選びを分かりやすく。</span></h1><p className="hero-lead">GPU・自作PC・ローカルAIについて、<br className="desktop-break" />初心者にも分かるように解説するサイト。</p><div className="hero-actions"><Link href="/gpu/" className="button">GPU記事を見る <span>↗</span></Link><Link href="/beginner/" className="button button-outline">はじめての方へ</Link></div><div className="hero-note"><span>01</span> 数字は出典と条件を確認。実測のない値は掲載しません。</div></div><div className="hero-art" aria-hidden="true"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><div className="gpu-illustration"><span className="gpu-top">PC NOTE / GRAPHICS</span><div className="gpu-line"/><span className="gpu-chip">GPU</span><span className="gpu-fan">◎</span><span className="gpu-fan fan-two">◎</span><span className="gpu-bottom">VRAM · POWER · WORKLOAD</span></div><span className="art-label label-a">REAL SPECS</span><span className="art-label label-b">NO MADE-UP BENCHMARKS</span></div></div></section>
    <section className="container section-block"><div className="section-heading"><div><p className="eyebrow">START HERE</p><h2>目的から記事を探す</h2></div><Link href="/about/" className="text-link">サイトの編集方針 <span>↗</span></Link></div><div className="category-grid">{categories.map((item, i) => <Link href={`/${item.slug}/`} key={item.slug} className="category-card"><span className="category-number">0{i + 1}</span><span className="category-icon">{["▧", "◉", "⌁", "▱", "⌘", "↗"][i]}</span><h3>{item.name}</h3><p>{item.description}</p><span className="arrow">↗</span></Link>)}</div></section>
    <section className="section-tint"><div className="container section-block"><div className="section-heading"><div><p className="eyebrow">EDITOR’S PICKS</p><h2>おすすめ記事</h2></div><Link href="/gpu/" className="text-link">記事一覧へ <span>↗</span></Link></div><div className="article-grid">{featured.map((article) => <ArticleCard article={article} key={article.slug} featured />)}</div></div></section>
    {categories.slice(0, 4).map((category) => { const list = articles.filter((a) => a.category === category.name).slice(0, 2); return <section className="container section-block category-preview" key={category.slug}><div className="section-heading"><div><p className="eyebrow">{category.slug.toUpperCase()}</p><h2>{category.name}</h2></div><Link href={`/${category.slug}/`} className="text-link">カテゴリを見る <span>↗</span></Link></div><div className="article-grid">{list.map((article) => <ArticleCard article={article} key={article.slug} />)}</div></section>; })}
    <section className="container trust-strip"><span className="trust-icon">i</span><div><strong>価格・性能の変化を前提に。</strong><p>価格やベンチマークは条件と時期を添えて扱います。未計測の製品を「検証済み」とは表現しません。</p></div><Link href="/about/" className="text-link">編集方針 <span>↗</span></Link></section>
  </>;
}
